packages:
  - apps/*
  - packages/*

catalog:
  lucide-react: ^0.511.0
  tailwindcss: ^4.1.10
  typescript: ^5.6.3
  '@types/node': ^22
  biome: ^1.9.4
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0

ignoredBuiltDependencies:
  - supabase
